---
version: '3'
services:
  maven:
    build: maven
    volumes:
      - maven:/app/boxfuse-sample-java-war-hello/target/
  tomcat:
    image: tomcat:jre8-alpine
    ports:
      - "8080:8080"
    volumes:
      - maven:/usr/local/tomcat/webapps
volumes:
  maven:
