---
version: '3'
services:
  dev:
    build: maven
    volumes:
      - mydata:/app/boxfuse-sample-java-war-hello/target/
  prod:
    image: tomcat:9.0.8-jre8-alpine
    ports:
      - "8080:8080"
    volumes:
      - mydata:/usr/local/tomcat/webapps
volumes:
  mydata:
